services:
  mongodb:
    image: mongo:6.0
    container_name: infractions-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    image: nihitana29/infractions-backend:latest
    container_name: infractions-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/infractions_routieres
      - CLIENT_URL=http://localhost:8081
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    image: nihitana29/infractions-frontend:latest
    container_name: infractions-frontend
    ports:
      - "8081:8080"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo-data:

networks:
  jenkins_net:
    external: true
    name: jenkinsdocker_default
